Repository poteto-go/poteto, pull requests merged in 2024-12, with the labels that each got.

#131 20241201/opt middleware search insert
  middleware_tree.go
  utils/cushion.go
Labels: release brocking

#125 `ctx.DebugParam()` returns All HttpParam
  CHANGELOG.md
  README.md
  context.go
  context_test.go
  http_param.go
  http_param_test.go
Labels: release brocking

#122 urlの最後以外におけるパラメータ
  CHANGELOG.md
  app_test.go
  poteto.go
  poteto_test.go
  route.go
  route_test.go
Labels: release brocking

#133 poteto-cli released
  .github/workflows/test.yaml
  .gitignore
  CHANGELOG.md
  README.md
  cmd/engine/new.go
  cmd/engine/new_test.go
  cmd/poteto-cli/main.go
  cmd/poteto-cli/main_test.go
  cmd/template/defalut.go
  cmd/template/fast.go
  constant/constant.go
  go.mod
  go.sum
  run_test.sh
  utils_for_test.go
Labels: release brocking

#140 appropriate error messages ( エラーの内容を具体化する
  context.go
  ip_handler.go
  middleware/jws.go
  router.go
  utils/cushion.go
Labels: release brocking

#141 単体テストの追加
  middleware/jws_test.go
  utils/cushion_test.go
Labels: release brocking

#144 `Poteto.RunTLS(addr, cert, key)` starts https server
  _fixture/README.md
  _fixture/certs/cert.pem
  _fixture/certs/check_certificate.sh
  _fixture/certs/create_local_certs.sh
  _fixture/certs/key.pem
  poteto.go
  poteto_test.go
  utils/cushion.go
Labels: release brocking

#154 JSON RPC
  context.go
  context_test.go
  go.mod
  go.sum
  poteto_rpc.go
  poteto_rpc_test.go
  utils/cushion.go
  utils/cushion_test.go
  utils_for_test.go
Labels: release brocking

#158 `PotetoJSONRPCAdapter`がクラスをチェックしない問題の修正
  poteto_rpc.go
  poteto_rpc_test.go
  utils_for_test.go
Labels: bug

#160 `examples`の追加
  .github/workflows/test-1_23.yaml
  exmaples/README.md
  exmaples/api/go.mod
  exmaples/api/go.sum
  exmaples/api/main.go
  exmaples/fast-api/go.mod
  exmaples/fast-api/go.sum
  exmaples/fast-api/main.go
  exmaples/jsonrpc/go.mod
  exmaples/jsonrpc/go.sum
  exmaples/jsonrpc/main.go
Labels: documentation

#168 FEAT: -d | --docker gen with Dockerfile & docker-compose.yaml
  cmd/engine/new.go
  cmd/engine/new_test.go
  cmd/template/docker.go
  cmd/template/docker_compose.go
Labels: feature

#173 REFACTOR: poteto-cli
  .github/workflows/test-1_21.yaml
  .github/workflows/test-1_22.yaml
  .github/workflows/test-1_23.yaml
  cmd/cmd-new/cmd_new.go
  cmd/cmd-new/cmd_new_test.go
  cmd/engine/engine_new.go
  cmd/engine/engine_new_test.go
  cmd/engine/new.go
  cmd/engine/new_test.go
  cmd/poteto-cli/main.go
  cmd/poteto-cli/main_test.go
  poteto.go
  run_test.sh
Labels: bug, enhancement, poteto-cli
